name: Continuous Integration
on:
  pull_request:

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}


jobs:
  test-kubernetes-code:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Datree against code
        uses: datreeio/action-datree@main
        with:
          path: '**/*.yaml'
          cliArguments: '--only-k8s-files'